## create a dataframe views with two columns

In [26]:
import pandas as pd

In [27]:
data = pd.read_csv(
    "../../data/feed-views.log",
    sep="\t",
    header=None,
    names=["datetime", "user"]
)
data["datetime"] = pd.to_datetime(data["datetime"])

data["year"] = data["datetime"].dt.year
data["month"] = data["datetime"].dt.month
data["day"] = data["datetime"].dt.day
data["hour"] = data["datetime"].dt.hour
data["minute"] = data["datetime"].dt.minute
data["second"] = data["datetime"].dt.second

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1076 entries, 0 to 1075
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1076 non-null   datetime64[ns]
 1   user      1076 non-null   object
 2   year      1076 non-null   int32
 3   month     1076 non-null   int32
 4   day       1076 non-null   int32
 5   hour      1076 non-null   int32
 6   minute    1076 non-null   int32
 7   second    1076 non-null   int32
dtypes: datetime64[ns](1), int32(6), object(1)
memory usage: 42.2+ KB

## create the new column daytime

In [29]:
bins = [0, 4, 7, 11, 17, 20, 24]
labels = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']

data['daytime'] = pd.cut(data['hour'], bins=bins, labels=labels, right=False)

data.set_index('user', inplace=True)

In [30]:
data.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

## calculate the number of elements in your dataframe

In [31]:
data.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [32]:
data.daytime.value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

## sort values in your dataframe

In [33]:
data_sorted = data.sort_values(by=['hour', 'minute', 'second'], ascending=[True, True, True])

## calculate the minimum and maximum

In [34]:
night_mask = data['daytime'] == 'night'
max_hour_night = data.loc[night_mask, 'hour'].max()

In [35]:
max_hour_night

3

In [36]:
morning_mask = data['daytime'] == 'morning'
min_hour_morning = data.loc[morning_mask, 'hour'].min()

In [37]:
min_hour_morning

8

In [38]:
data.loc[
    (data['daytime'] == 'night') & (data['hour'] == max_hour_night)
].head(1)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night

In [39]:
data.loc[
    (data['daytime'] == 'morning') & (data['hour'] == min_hour_morning)
].head(1)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning

In [40]:
data

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
...,...,...,...,...,...,...,...,...
valentina,2020-05-21 18:45:20.441142,2020,5,21,18,45,20,early evening
maxim,2020-05-21 23:03:06.457819,2020,5,21,23,3,6,evening
pavel,2020-05-21 23:23:49.995349,2020,5,21,23,23,49,evening
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
artem,2020-05-22 10:36:14.662600,2020,5,22,10,36,14,morning

In [41]:
a = data['hour'].mode()[0]
print(a)

22

In [42]:
data['daytime'].mode()[0]

'evening'

## show the earliest and the latest 3 hours

In [43]:
data[data['daytime'] == 'morning'].nsmallest(3, columns='hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,morning
artem,2020-04-24 09:42:47.598208,2020,4,24,9,42,47,morning

In [44]:
data[data['daytime'] == 'morning'].nlargest(3, columns='hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-18 10:53:52.623447,2020,4,18,10,53,52,morning
maxim,2020-04-18 10:56:55.833899,2020,4,18,10,56,55,morning
konstantin,2020-04-18 10:57:37.331258,2020,4,18,10,57,37,morning

## use the method describe() to get the basic statistics for the columns

In [45]:
data.describe()

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [46]:
iqr = data.describe().loc['75%']['hour'] - data.describe().loc['25%']['hour']
print(iqr)

9.0