# Day 09. Exercise 01
# Gridsearch

## 0. Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from tqdm import tqdm
from sklearn.metrics import accuracy_score

## 1. Preprocessing

1. Read the file [`day-of-week-not-scaled.csv`](https://drive.google.com/file/d/1AlGvsJDSzPT_70caausx8bFuupIEZkfh/view?usp=sharing). It is similar to the one from the previous exercise, but this time we did not scale continuous features (we are not going to use logreg anymore). Don't forget to enrich the table with the 'dayofweek' column from the previous day's .csv-file.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [2]:
df = pd.read_csv('../../data/day-of-week-not-scaled.csv')

old_df = pd.read_csv('../../data/dayofweek.csv')

df['dayofweek'] = old_df['dayofweek']

X = df.drop('dayofweek', axis=1)
y = df['dayofweek']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

## 2. SVM gridsearch

1. Using `GridSearchCV` try different parameters of kernel (`linear`, `rbf`, `sigmoid`), C (`0.01`, `0.1`, `1`, `1.5`, `5`, `10`), gamma (`scale`, `auto`), class_weight (`balanced`, `None`) use `random_state=21` and `probability=True` and get the best combination of them in terms of accuracy.
2. Create a dataframe from the results of the gridsearch and sort it ascendingly by the `rank_test_score`. Check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [3]:
svc = SVC(random_state=21, probability=True)
param_grid = {
    'kernel': ['linear', 'rbf', 'sigmoid'],
    'C': (0.01, 0.1, 1, 1.5, 5, 10),
    'gamma': ['scale', 'auto'],
    'class_weight': ['balanced', None]
}
grid = GridSearchCV(estimator=svc, 
                    param_grid=param_grid,
                    cv=3, 
                    scoring='accuracy',
                    n_jobs=-1)

In [4]:
grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(probability=True, random_state=21), n_jobs=-1,
             param_grid={'C': (0.01, 0.1, 1, 1.5, 5, 10),
                         'class_weight': ['balanced', None],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'sigmoid']},
             scoring='accuracy')

In [5]:
res = pd.DataFrame(grid.cv_results_)
res = res.sort_values(by='rank_test_score')
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_class_weight,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
64,0.301636,0.012407,0.026247,0.002492,10.0,balanced,auto,rbf,"{'C': 10, 'class_weight': 'balanced', 'gamma':...",0.855556,0.841871,0.835189,0.844205,0.008477,1
70,0.359281,0.044096,0.031138,0.009664,10.0,None,auto,rbf,"{'C': 10, 'class_weight': None, 'gamma': 'auto...",0.853333,0.848552,0.826281,0.842722,0.011789,2
58,0.301587,0.040414,0.042851,0.023123,5.0,None,auto,rbf,"{'C': 5, 'class_weight': None, 'gamma': 'auto'...",0.793333,0.781737,0.775056,0.783375,0.007551,3
52,0.301548,0.019664,0.028783,0.002020,5.0,balanced,auto,rbf,"{'C': 5, 'class_weight': 'balanced', 'gamma': ...",0.795556,0.766147,0.770601,0.777435,0.012942,4
60,39.211635,2.049984,0.012195,0.000905,10.0,balanced,scale,linear,"{'C': 10, 'class_weight': 'balanced', 'gamma':...",0.724444,0.761693,0.670379,0.718839,0.037489,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,0.437758,0.023601,0.026452,0.001233,5.0,balanced,auto,sigmoid,"{'C': 5, 'class_weight': 'balanced', 'gamma': ...",0.173333,0.106904,0.189310,0.156516,0.035682,68
65,0.396478,0.036631,0.026068,0.001126,10.0,balanced,auto,sigmoid,"{'C': 10, 'class_weight': 'balanced', 'gamma':...",0.135556,0.120267,0.167038,0.140954,0.019472,69
17,1.273490,0.205046,0.076992,0.005574,0.1,balanced,auto,sigmoid,"{'C': 0.1, 'class_weight': 'balanced', 'gamma'...",0.162222,0.082405,0.162584,0.135737,0.037711,70
41,0.702767,0.055566,0.031735,0.004847,1.5,balanced,auto,sigmoid,"{'C': 1.5, 'class_weight': 'balanced', 'gamma'...",0.082222,0.155902,0.073497,0.103874,0.036962,71
29,1.099948,0.038809,0.077203,0.012091,1.0,balanced,auto,sigmoid,"{'C': 1, 'class_weight': 'balanced', 'gamma': ...",0.062222,0.080178,0.060134,0.067511,0.008997,72

## 3. Decision tree

1. Using `GridSearchCV` try different parameters of `max_depth` (from `1` to `49`), `class_weight` (`balanced`, `None`) and `criterion` (`entropy` and `gini`) and get the best combination of them in terms of accuracy. Use `random_state=21`.
2. Create a dataframe from the results of the gridsearch and sort it ascendingly by the `rank_test_score`, check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [6]:
tree = DecisionTreeClassifier(random_state=21)
param_grid = {
    'max_depth': np.arange(1, 49),
    'class_weight': ('balanced', None),
    'criterion': ('entropy', 'gini')
}
grid = GridSearchCV(estimator=tree, 
                    param_grid=param_grid, 
                    cv=3,
                    scoring='accuracy',
                    n_jobs=-1)

grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=21), n_jobs=-1,
             param_grid={'class_weight': ('balanced', None),
                         'criterion': ('entropy', 'gini'),
                         'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])},
             scoring='accuracy')

In [7]:
res = pd.DataFrame(grid.cv_results_)
res = res.sort_values(by='rank_test_score')

In [8]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(res)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
168,0.005300,0.000815,0.002096,0.000238,None,gini,25,"{'class_weight': None, 'criterion': 'gini', 'm...",0.857778,0.881960,0.846325,0.862021,0.014854,1
183,0.004859,0.000460,0.001923,0.000118,None,gini,40,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
186,0.005845,0.001590,0.002096,0.000050,None,gini,43,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
185,0.005658,0.001325,0.003388,0.001181,None,gini,42,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
188,0.004280,0.000132,0.001889,0.000035,None,gini,45,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
189,0.004891,0.000434,0.001964,0.000191,None,gini,46,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
190,0.005111,0.000176,0.001999,0.000076,None,gini,47,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
187,0.005450,0.001534,0.002147,0.000267,None,gini,44,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
184,0.004681,0.000114,0.002056,0.000007,None,gini,41,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
175,0.004633,0.000162,0.002381,0.000369,None,gini,32,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
173,0.004573,0.000157,0.002187,0.000173,None,gini,30,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
174,0.004640,0.000272,0.002056,0.000027,None,gini,31,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
171,0.004866,0.000252,0.002250,0.000229,None,gini,28,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
170,0.004852,0.000277,0.002191,0.000288,None,gini,27,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
169,0.004774,0.000134,0.002235,0.000171,None,gini,26,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
191,0.005985,0.000875,0.002314,0.000309,None,gini,48,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
179,0.005745,0.000671,0.001962,0.000113,None,gini,36,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
182,0.004875,0.000234,0.002581,0.000897,None,gini,39,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
181,0.004751,0.000108,0.003248,0.000718,None,gini,38,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
180,0.005224,0.000381,0.002007,0.000183,None,gini,37,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
177,0.005948,0.001732,0.002639,0.000816,None,gini,34,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
178,0.006503,0.001851,0.002006,0.000043,None,gini,35,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
176,0.004597,0.000028,0.002086,0.000117,None,gini,33,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
172,0.004666,0.000053,0.002122,0.000116,None,gini,29,"{'class_weight': None, 'criterion': 'gini', 'm...",0.848889,0.881960,0.846325,0.859058,0.016228,2
167,0.004717,0.000186,0.001958,0.000013,None,gini,24,"{'class_weight': None, 'criterion': 'gini', 'm...",0.851111,0.881960,0.839644,0.857572,0.017869,25
80,0.006450,0.000459,0.002374,0.000082,balanced,gini,33,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
82,0.007388,0.000826,0.002251,0.000019,balanced,gini,35,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
81,0.006721,0.000757,0.002963,0.000875,balanced,gini,34,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
84,0.006504,0.000136,0.002417,0.000179,balanced,gini,37,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
85,0.007085,0.000673,0.002471,0.000093,balanced,gini,38,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
86,0.006651,0.000409,0.002612,0.000264,balanced,gini,39,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
83,0.006764,0.000161,0.002427,0.000334,balanced,gini,36,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
78,0.008021,0.001454,0.002404,0.000132,balanced,gini,31,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
73,0.006838,0.000658,0.003043,0.000965,balanced,gini,26,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
75,0.007318,0.000685,0.002277,0.000056,balanced,gini,28,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
74,0.007058,0.000830,0.002781,0.000402,balanced,gini,27,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
79,0.007719,0.001407,0.002348,0.000036,balanced,gini,32,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
77,0.007001,0.000110,0.002856,0.000323,balanced,gini,30,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
76,0.007896,0.002043,0.002977,0.000487,balanced,gini,29,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
87,0.007373,0.000586,0.002851,0.000389,balanced,gini,40,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
88,0.007371,0.000525,0.002371,0.000145,balanced,gini,41,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
95,0.006226,0.000164,0.002455,0.000165,balanced,gini,48,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
93,0.006817,0.000712,0.003380,0.001402,balanced,gini,46,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
94,0.006647,0.000208,0.002259,0.000105,balanced,gini,47,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
91,0.007353,0.001854,0.004187,0.001146,balanced,gini,44,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
90,0.006835,0.000530,0.002800,0.000618,balanced,gini,43,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
89,0.007237,0.000338,0.002421,0.000184,balanced,gini,42,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
92,0.010014,0.001419,0.002246,0.000028,balanced,gini,45,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.870824,0.824053,0.856811,0.023244,26
72,0.009197,0.002735,0.002603,0.000278,balanced,gini,25,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.868597,0.824053,0.856069,0.022816,49
71,0.007286,0.000225,0.002478,0.000205,balanced,gini,24,"{'class_weight': 'balanced', 'criterion': 'gin...",0.875556,0.868597,0.824053,0.856069,0.022816,49
165,0.004564,0.000045,0.002012,0.000060,None,gini,22,"{'class_weight': None, 'criterion': 'gini', 'm...",0.842222,0.881960,0.839644,0.854609,0.019369,51
164,0.004512,0.000078,0.002047,0.000083,None,gini,21,"{'class_weight': None, 'criterion': 'gini', 'm...",0.844444,0.881960,0.835189,0.853865,0.020223,52
166,0.004619,0.000050,0.001970,0.000076,None,gini,23,"{'class_weight': None, 'criterion': 'gini', 'm...",0.840000,0.881960,0.837416,0.853125,0.020416,53
161,0.005438,0.000687,0.002389,0.000419,None,gini,18,"{'class_weight': None, 'criterion': 'gini', 'm...",0.846667,0.879733,0.832962,0.853121,0.019632,54
162,0.010106,0.006736,0.004087,0.002598,None,gini,19,"{'class_weight': None, 'criterion': 'gini', 'm...",0.842222,0.879733,0.835189,0.852381,0.019552,55
70,0.006498,0.000382,0.002747,0.000411,balanced,gini,23,"{'class_weight': 'balanced', 'criterion': 'gin...",0.868889,0.864143,0.824053,0.852362,0.020110,56
68,0.008210,0.000892,0.003477,0.000582,balanced,gini,21,"{'class_weight': 'balanced', 'criterion': 'gin...",0.873333,0.859688,0.824053,0.852358,0.020775,57
160,0.005440,0.000562,0.002055,0.000058,None,gini,17,"{'class_weight': None, 'criterion': 'gini', 'm...",0.828889,0.881960,0.844098,0.851649,0.022314,58
163,0.005037,0.000674,0.002129,0.000130,None,gini,20,"{'class_weight': None, 'criterion': 'gini', 'm...",0.844444,0.886414,0.824053,0.851637,0.025962,59
69,0.007428,0.001094,0.002588,0.000549,balanced,gini,22,"{'class_weight': 'balanced', 'criterion': 'gin...",0.866667,0.864143,0.824053,0.851621,0.019520,60
67,0.008918,0.001203,0.002376,0.000248,balanced,gini,20,"{'class_weight': 'balanced', 'criterion': 'gin...",0.866667,0.861915,0.824053,0.850878,0.019067,61
18,0.007456,0.000810,0.002934,0.000864,balanced,entropy,19,"{'class_weight': 'balanced', 'criterion': 'ent...",0.857778,0.877506,0.815145,0.850143,0.026025,62
19,0.006773,0.000228,0.002343,0.000158,balanced,entropy,20,"{'class_weight': 'balanced', 'criterion': 'ent...",0.860000,0.877506,0.808463,0.848656,0.029306,63
66,0.006847,0.000496,0.002273,0.000122,balanced,gini,19,"{'class_weight': 'balanced', 'criterion': 'gin...",0.862222,0.859688,0.824053,0.848655,0.017426,64
121,0.006270,0.000618,0.003295,0.000732,None,entropy,26,"{'class_weight': None, 'criterion': 'entropy',...",0.864444,0.839644,0.837416,0.847168,0.012250,65
65,0.006315,0.000144,0.002253,0.000027,balanced,gini,18,"{'class_weight': 'balanced', 'criterion': 'gin...",0.864444,0.857461,0.817372,0.846426,0.020741,66
24,0.007054,0.000347,0.002306,0.000098,balanced,entropy,25,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
25,0.008464,0.002214,0.003217,0.001510,balanced,entropy,26,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
27,0.008155,0.001147,0.002335,0.000022,balanced,entropy,28,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
30,0.007336,0.000772,0.002643,0.000361,balanced,entropy,31,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
26,0.007560,0.000491,0.003804,0.001779,balanced,entropy,27,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
31,0.007199,0.000446,0.002378,0.000140,balanced,entropy,32,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
21,0.006804,0.000127,0.002216,0.000123,balanced,entropy,22,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
22,0.006505,0.000052,0.002412,0.000128,balanced,entropy,23,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
29,0.008508,0.000710,0.002295,0.000197,balanced,entropy,30,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
23,0.007456,0.000211,0.002588,0.000171,balanced,entropy,24,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
28,0.007146,0.000731,0.002832,0.000742,balanced,entropy,29,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
34,0.013111,0.006317,0.002668,0.000468,balanced,entropy,35,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
33,0.007289,0.000232,0.002289,0.000149,balanced,entropy,34,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
32,0.008179,0.002039,0.003077,0.000956,balanced,entropy,33,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
47,0.008851,0.001131,0.002496,0.000426,balanced,entropy,48,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
46,0.007325,0.000176,0.003026,0.000981,balanced,entropy,47,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
45,0.008670,0.001191,0.002395,0.000026,balanced,entropy,46,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
44,0.008142,0.000520,0.004390,0.001051,balanced,entropy,45,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
43,0.008973,0.001769,0.002762,0.000842,balanced,entropy,44,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
42,0.008493,0.001448,0.003856,0.001188,balanced,entropy,43,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
41,0.007457,0.000566,0.002821,0.000337,balanced,entropy,42,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
40,0.008503,0.001620,0.004069,0.002473,balanced,entropy,41,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
39,0.007511,0.000947,0.002362,0.000061,balanced,entropy,40,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
38,0.008322,0.002268,0.002658,0.000051,balanced,entropy,39,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
37,0.007789,0.001199,0.002736,0.000426,balanced,entropy,38,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
36,0.007829,0.000620,0.002930,0.000956,balanced,entropy,37,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
35,0.007657,0.000643,0.002486,0.000304,balanced,entropy,36,"{'class_weight': 'balanced', 'criterion': 'ent...",0.851111,0.877506,0.808463,0.845693,0.028446,67
17,0.007020,0.000931,0.002297,0.000056,balanced,entropy,18,"{'class_weight': 'balanced', 'criterion': 'ent...",0.857778,0.864143,0.815145,0.845688,0.021753,94
142,0.009711,0.002197,0.003281,0.000870,None,entropy,47,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
143,0.008733,0.001277,0.002584,0.000318,None,entropy,48,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
116,0.008255,0.000739,0.003440,0.000990,None,entropy,21,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
125,0.014158,0.004420,0.003224,0.000953,None,entropy,30,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
123,0.011837,0.004084,0.002859,0.000620,None,entropy,28,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
122,0.007377,0.000747,0.002668,0.000412,None,entropy,27,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
124,0.009194,0.002384,0.003429,0.000476,None,entropy,29,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
133,0.012796,0.000673,0.005405,0.000543,None,entropy,38,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
134,0.012063,0.004035,0.004723,0.001882,None,entropy,39,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
135,0.013984,0.001950,0.005928,0.001294,None,entropy,40,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
136,0.012537,0.001261,0.006289,0.001103,None,entropy,41,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
137,0.012443,0.000166,0.005532,0.001227,None,entropy,42,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
138,0.008979,0.001296,0.003167,0.000814,None,entropy,43,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
139,0.008533,0.001764,0.004893,0.001897,None,entropy,44,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
140,0.010415,0.001430,0.003344,0.000731,None,entropy,45,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
141,0.010339,0.002190,0.006722,0.001782,None,entropy,46,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
126,0.006226,0.000620,0.002417,0.000028,None,entropy,31,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
127,0.008572,0.003666,0.005847,0.004766,None,entropy,32,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
128,0.025433,0.002415,0.010311,0.000554,None,entropy,33,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
129,0.023269,0.001323,0.012618,0.002351,None,entropy,34,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
130,0.011118,0.005027,0.007290,0.002904,None,entropy,35,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
131,0.010291,0.001009,0.007101,0.000906,None,entropy,36,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
132,0.011632,0.000567,0.005997,0.000566,None,entropy,37,"{'class_weight': None, 'criterion': 'entropy',...",0.860000,0.839644,0.837416,0.845687,0.010162,95
20,0.007725,0.000780,0.002372,0.000343,balanced,entropy,21,"{'class_weight': 'balanced', 'criterion': 'ent...",0.848889,0.877506,0.808463,0.844953,0.028324,118
119,0.006546,0.000525,0.002649,0.000123,None,entropy,24,"{'class_weight': None, 'criterion': 'entropy',...",0.857778,0.839644,0.837416,0.844946,0.009119,119
120,0.007784,0.001244,0.004349,0.001590,None,entropy,25,"{'class_weight': None, 'criterion': 'entropy',...",0.857778,0.839644,0.837416,0.844946,0.009119,119
115,0.007858,0.001681,0.002979,0.001061,None,entropy,20,"{'class_weight': None, 'criterion': 'entropy',...",0.866667,0.837416,0.830735,0.844939,0.015604,121
159,0.005607,0.000778,0.002331,0.000473,None,gini,16,"{'class_weight': None, 'criterion': 'gini', 'm...",0.831111,0.879733,0.821826,0.844223,0.025393,122
118,0.008207,0.001875,0.002127,0.000052,None,entropy,23,"{'class_weight': None, 'criterion': 'entropy',...",0.855556,0.839644,0.837416,0.844205,0.008077,123
15,0.006559,0.000056,0.002191,0.000099,balanced,entropy,16,"{'class_weight': 'balanced', 'criterion': 'ent...",0.857778,0.868597,0.806236,0.844204,0.027208,124
117,0.007330,0.001766,0.002782,0.000698,None,entropy,22,"{'class_weight': None, 'criterion': 'entropy',...",0.853333,0.839644,0.837416,0.843464,0.007037,125
114,0.006599,0.001390,0.002864,0.000868,None,entropy,19,"{'class_weight': None, 'criterion': 'entropy',...",0.853333,0.837416,0.837416,0.842722,0.007503,126

## 4. Random forest

1. Using `GridSearchCV` try different parameters of `n_estimators` (`5`, `10`, `50`, `100`), `max_depth` (from `1` to `49`), `class_weight` (`balanced`, `None`) and `criterion` (`entropy` and `gini`) and get the best combination of them in terms of accuracy. Use random_state=21.
2. Create a dataframe from the results of the gridsearch and sort it ascendengly by the `rank_test_score`, check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [9]:
tree = RandomForestClassifier(random_state=21)

params = {
    'n_estimators': [5, 10, 50, 100],
    'max_depth': np.arange(1, 50),          
    'class_weight': ['balanced', None],
    'criterion': ['entropy', 'gini']
}

grid = GridSearchCV(
    estimator=tree,
    param_grid=params,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=21), n_jobs=-1,
             param_grid={'class_weight': ['balanced', None],
                         'criterion': ['entropy', 'gini'],
                         'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'n_estimators': [5, 10, 50, 100]},
             scoring='accuracy')

In [10]:
res = pd.DataFrame(grid.cv_results_)
res = res.sort_values(by='rank_test_score')

In [11]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(res)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
783,0.195141,0.004235,0.013734,0.000499,None,gini,49,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
755,0.197899,0.001462,0.013935,0.000157,None,gini,42,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
779,0.196969,0.002129,0.013645,0.000120,None,gini,48,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
759,0.195308,0.001752,0.013779,0.000049,None,gini,43,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
727,0.220219,0.003276,0.014195,0.000547,None,gini,35,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
731,0.202481,0.007881,0.013790,0.000096,None,gini,36,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
763,0.210374,0.002799,0.015915,0.000285,None,gini,44,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
735,0.212735,0.003048,0.015317,0.000796,None,gini,37,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
719,0.232480,0.026527,0.015289,0.001124,None,gini,33,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
767,0.197424,0.000903,0.014260,0.000612,None,gini,45,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
747,0.208896,0.008478,0.015069,0.000308,None,gini,40,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
739,0.196205,0.003610,0.013850,0.000078,None,gini,38,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
771,0.195614,0.002664,0.013820,0.000021,None,gini,46,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
775,0.207817,0.001929,0.014196,0.000503,None,gini,47,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
751,0.195136,0.002589,0.014090,0.000274,None,gini,41,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
743,0.197295,0.003201,0.013770,0.000100,None,gini,39,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.908686,0.881960,0.899845,0.012647,1
707,0.195515,0.001524,0.014559,0.000791,None,gini,30,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.906667,0.910913,0.879733,0.899104,0.013807,17
723,0.199696,0.003202,0.014137,0.000061,None,gini,34,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.906459,0.881960,0.899103,0.012162,18
686,0.105867,0.002426,0.008772,0.000808,None,gini,25,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.906667,0.908686,0.879733,0.898362,0.013198,19
711,0.255555,0.072769,0.014095,0.000402,None,gini,31,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.906667,0.904232,0.884187,0.898362,0.010072,19
715,0.243223,0.024678,0.015425,0.000861,None,gini,32,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.908889,0.906459,0.879733,0.898360,0.013209,21
670,0.097363,0.001823,0.008096,0.000076,None,gini,21,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.913333,0.906459,0.875278,0.898357,0.016558,22
710,0.102462,0.002030,0.008062,0.000119,None,gini,31,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.902004,0.888641,0.897623,0.006351,23
678,0.211638,0.052993,0.011988,0.003801,None,gini,23,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.904444,0.904232,0.884187,0.897621,0.009500,24
690,0.098755,0.001519,0.008255,0.000109,None,gini,26,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.904232,0.884187,0.896880,0.009013,25
694,0.100940,0.002807,0.008144,0.000275,None,gini,27,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.904444,0.904232,0.881960,0.896879,0.010550,26
687,0.211953,0.001111,0.015546,0.000261,None,gini,25,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.906667,0.902004,0.881960,0.896877,0.010718,27
718,0.130920,0.009471,0.015692,0.004416,None,gini,33,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.900000,0.904232,0.884187,0.896140,0.008626,28
726,0.110361,0.001815,0.008266,0.000332,None,gini,35,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.902004,0.884187,0.896138,0.008451,29
286,0.204916,0.032212,0.014416,0.006555,balanced,gini,23,50,"{'class_weight': 'balanced', 'criterion': 'gin...",0.900000,0.910913,0.875278,0.895397,0.014907,30
515,0.210080,0.001623,0.013739,0.000268,None,entropy,31,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
523,0.206288,0.001180,0.013861,0.000386,None,entropy,33,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
563,0.245433,0.008951,0.017245,0.001545,None,entropy,43,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
535,0.225496,0.007457,0.015425,0.000129,None,entropy,36,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
587,0.314740,0.074203,0.019801,0.001666,None,entropy,49,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
583,0.412423,0.157214,0.025669,0.014558,None,entropy,48,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
579,0.477588,0.093088,0.025779,0.010849,None,entropy,47,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
527,0.206584,0.002108,0.013777,0.000105,None,entropy,34,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
551,0.205217,0.001240,0.014089,0.000447,None,entropy,40,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
547,0.205999,0.001523,0.013906,0.000324,None,entropy,39,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
539,0.205235,0.001567,0.013816,0.000014,None,entropy,37,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
543,0.211877,0.002769,0.014584,0.000893,None,entropy,38,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
555,0.214601,0.004701,0.014146,0.000523,None,entropy,41,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
559,0.234509,0.010003,0.015207,0.000417,None,entropy,42,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
567,0.255414,0.019172,0.016803,0.002755,None,entropy,44,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
531,0.210118,0.004585,0.013868,0.000286,None,entropy,35,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
575,0.576551,0.068720,0.032291,0.011347,None,entropy,46,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
571,0.459978,0.117892,0.025211,0.011681,None,entropy,45,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.908686,0.877506,0.895397,0.013139,31
746,0.103176,0.003303,0.009062,0.000556,None,gini,40,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
738,0.098838,0.000476,0.008721,0.000611,None,gini,38,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
758,0.104187,0.002575,0.008007,0.000066,None,gini,43,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
754,0.097639,0.000510,0.008101,0.000129,None,gini,42,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
782,0.098898,0.001826,0.008175,0.000132,None,gini,49,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
722,0.099555,0.003588,0.008537,0.000342,None,gini,34,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
730,0.109504,0.002268,0.008095,0.000077,None,gini,36,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
734,0.102990,0.003549,0.008395,0.000222,None,gini,37,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
762,0.101390,0.003332,0.008017,0.000083,None,gini,44,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
495,0.205801,0.001872,0.013807,0.000030,None,entropy,26,100,"{'class_weight': None, 'criterion': 'entropy',...",0.902222,0.908686,0.875278,0.895396,0.014468,49
507,0.208587,0.003092,0.013661,0.000139,None,entropy,29,100,"{'class_weight': None, 'criterion': 'entropy',...",0.902222,0.908686,0.875278,0.895396,0.014468,49
742,0.099236,0.000821,0.008084,0.000092,None,gini,39,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
774,0.102390,0.002265,0.008154,0.000242,None,gini,47,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
770,0.098736,0.002132,0.008035,0.000046,None,gini,46,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
778,0.099156,0.000512,0.008371,0.000198,None,gini,48,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
750,0.103306,0.002879,0.008201,0.000149,None,gini,41,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
766,0.100022,0.002425,0.008114,0.000121,None,gini,45,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.899777,0.884187,0.895396,0.007988,49
706,0.100534,0.000517,0.008055,0.000129,None,gini,30,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.900000,0.904232,0.879733,0.894655,0.010692,66
714,0.105038,0.005156,0.007999,0.000045,None,gini,32,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.900000,0.899777,0.884187,0.894655,0.007402,67
519,0.220064,0.002717,0.015134,0.000656,None,entropy,32,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.906459,0.877506,0.894655,0.012410,67
699,0.195057,0.003102,0.014500,0.000370,None,gini,28,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.900000,0.908686,0.875278,0.894655,0.014153,67
475,0.310435,0.034129,0.015839,0.001693,None,entropy,21,100,"{'class_weight': None, 'criterion': 'entropy',...",0.902222,0.904232,0.877506,0.894653,0.012153,70
691,0.203399,0.004603,0.013913,0.000367,None,gini,26,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.904232,0.877506,0.894653,0.012153,70
695,0.196580,0.003765,0.014810,0.000773,None,gini,27,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.904444,0.902004,0.877506,0.894651,0.012165,72
663,0.208723,0.007400,0.014518,0.000855,None,gini,19,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.906667,0.904232,0.873051,0.894650,0.015305,73
502,0.112307,0.007714,0.008492,0.000703,None,entropy,28,50,"{'class_weight': None, 'criterion': 'entropy',...",0.897778,0.906459,0.877506,0.893914,0.012132,74
511,0.207603,0.002582,0.013740,0.000103,None,entropy,30,100,"{'class_weight': None, 'criterion': 'entropy',...",0.897778,0.906459,0.877506,0.893914,0.012132,74
683,0.211295,0.007912,0.014091,0.000669,None,gini,24,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.900000,0.902004,0.879733,0.893912,0.010060,76
470,0.115070,0.004953,0.009670,0.001772,None,entropy,20,50,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.899777,0.881960,0.893912,0.008452,76
503,0.225177,0.006178,0.015963,0.001603,None,entropy,28,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.906459,0.875278,0.893912,0.013437,76
679,0.221254,0.015270,0.019132,0.005548,None,gini,23,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.902222,0.902004,0.877506,0.893911,0.011601,79
275,0.240003,0.021892,0.014869,0.000847,balanced,gini,20,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.904444,0.904232,0.873051,0.893909,0.014749,80
479,0.251007,0.031450,0.013822,0.000071,None,entropy,22,100,"{'class_weight': None, 'criterion': 'entropy',...",0.904444,0.899777,0.877506,0.893909,0.011755,80
703,0.217848,0.002821,0.016226,0.001152,None,gini,29,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.904444,0.904232,0.873051,0.893909,0.014749,80
667,0.208172,0.001759,0.016717,0.002119,None,gini,20,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.906667,0.902004,0.873051,0.893907,0.014870,83
671,0.231174,0.049473,0.019285,0.007784,None,gini,21,100,"{'class_weight': None, 'criterion': 'gini', 'm...",0.911111,0.897550,0.873051,0.893904,0.015750,84
114,0.127671,0.006020,0.009594,0.000988,balanced,entropy,29,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.875278,0.893172,0.013139,85
499,0.221730,0.004996,0.014389,0.001156,None,entropy,27,100,"{'class_weight': None, 'criterion': 'entropy',...",0.897778,0.910913,0.870824,0.893172,0.016687,85
666,0.101796,0.002800,0.008489,0.000711,None,gini,20,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.900000,0.906459,0.873051,0.893170,0.014468,87
267,0.313221,0.060109,0.019760,0.005354,balanced,gini,18,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.902222,0.902004,0.875278,0.893168,0.012650,88
514,0.110213,0.003996,0.007978,0.000060,None,entropy,31,50,"{'class_weight': None, 'criterion': 'entropy',...",0.891111,0.906459,0.879733,0.892434,0.010951,89
327,0.331660,0.150141,0.015861,0.001200,balanced,gini,33,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.895556,0.906459,0.875278,0.892431,0.012920,90
339,0.376365,0.091798,0.019821,0.008114,balanced,gini,36,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.895556,0.906459,0.875278,0.892431,0.012920,90
182,0.144211,0.006268,0.011551,0.002125,balanced,entropy,46,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
194,0.124050,0.002372,0.010054,0.000777,balanced,entropy,49,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
190,0.113358,0.004880,0.008375,0.000127,balanced,entropy,48,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
178,0.115435,0.003768,0.011433,0.002971,balanced,entropy,45,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
174,0.185002,0.060447,0.009432,0.001161,balanced,entropy,44,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
186,0.118443,0.008132,0.008187,0.000065,balanced,entropy,47,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
142,0.124979,0.006012,0.009994,0.001521,balanced,entropy,36,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
134,0.117652,0.002627,0.009399,0.000794,balanced,entropy,34,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
138,0.109203,0.002146,0.008140,0.000043,balanced,entropy,35,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
126,0.117346,0.001439,0.009211,0.001380,balanced,entropy,32,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
122,0.123829,0.006418,0.008336,0.000112,balanced,entropy,31,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
118,0.116656,0.004667,0.009652,0.001164,balanced,entropy,30,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.908686,0.870824,0.892429,0.015913,92
130,0.123769,0.008700,0.009669,0.001216,balanced,entropy,33,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
146,0.138830,0.029492,0.008650,0.000526,balanced,entropy,37,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
150,0.135098,0.006686,0.010358,0.002147,balanced,entropy,38,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
162,0.115836,0.005714,0.009492,0.000930,balanced,entropy,41,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
702,0.102715,0.002904,0.008707,0.000688,None,gini,29,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.897778,0.904232,0.875278,0.892429,0.012410,92
158,0.126400,0.005175,0.009983,0.001581,balanced,entropy,40,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
170,0.142313,0.031259,0.009114,0.001241,balanced,entropy,43,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
166,0.122370,0.006861,0.009423,0.000865,balanced,entropy,42,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
154,0.110805,0.004664,0.008135,0.000063,balanced,entropy,39,50,"{'class_weight': 'balanced', 'criterion': 'ent...",0.897778,0.906459,0.873051,0.892429,0.014153,92
698,0.108794,0.004304,0.008279,0.000427,None,gini,28,50,"{'class_weight': None, 'criterion': 'gini', 'm...",0.900000,0.899777,0.877506,0.892428,0.010552,113
491,0.225180,0.009913,0.016299,0.002035,None,entropy,25,100,"{'class_weight': None, 'criterion': 'entropy',...",0.900000,0.902004,0.875278,0.892428,0.012154,113
274,0.147876,0.018281,0.011506,0.001160,balanced,gini,20,50,"{'class_weight': 'balanced', 'criterion': 'gin...",0.900000,0.904232,0.873051,0.892428,0.013810,113
79,0.227404,0.017570,0.014572,0.000829,balanced,entropy,20,100,"{'class_weight': 'balanced', 'criterion': 'ent...",0.902222,0.913140,0.861915,0.892426,0.022030,116
462,0.106032,0.000869,0.008780,0.000556,None,entropy,18,50,"{'class_weight': None, 'criterion': 'entropy',...",0.902222,0.897550,0.877506,0.892426,0.010721,116
522,0.105495,0.002205,0.008048,0.000072,None,entropy,33,50,"{'class_weight': None, 'criterion': 'entropy',...",0.891111,0.904232,0.879733,0.891692,0.010010,118
518,0.106764,0.003647,0.008612,0.000680,None,entropy,32,50,"{'class_weight': None, 'criterion': 'entropy',...",0.891111,0.904232,0.879733,0.891692,0.010010,118
510,0.104492,0.001818,0.008242,0.000246,None,entropy,30,50,"{'class_weight': None, 'criterion': 'entropy',...",0.891111,0.899777,0.884187,0.891692,0.006378,120
482,0.112715,0.002596,0.008519,0.000675,None,entropy,23,50,"{'class_weight': None, 'criterion': 'entropy',...",0.895556,0.904232,0.875278,0.891689,0.012132,121
315,0.323897,0.056914,0.016693,0.002858,balanced,gini,30,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.895556,0.904232,0.875278,0.891689,0.012132,121
91,0.261237,0.016766,0.023807,0.011587,balanced,entropy,23,100,"{'class_weight': 'balanced', 'criterion': 'ent...",0.895556,0.910913,0.868597,0.891689,0.017491,121
335,0.317942,0.042827,0.034676,0.025993,balanced,gini,35,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.895556,0.906459,0.873051,0.891689,0.013910,121

## 5. Progress bar

Gridsearch can be a quite long process and you may find yourself wondering when it will end.
1. Create a manual gridsearch for the same parameters values of random forest iterating through the list of the possible values and calculating `cross_val_score` for each combination. Try to increase `n_jobs`. The value `cv` for `cross_val_score` is 5.
2. Track the progress using the library `tqdm.notebook`.
3. Create a dataframe from the results of the gridsearch with the columns corresponding to the names of the parameters and `mean_accuracy` and `std_accuracy`.
4. Sort it descendingly by the `mean_accuracy`, check if there is a huge difference between different combinations (sometimes a simpler model may give a comparable result).

In [12]:
from itertools import product
results = []

n_estimators_grid = [5, 10, 50, 100]
max_depth_grid    = list(np.arange(1, 50))
class_weight_grid = ['balanced', None]
criterion_grid    = ['entropy', 'gini']

param_grid = product(n_estimators_grid,
                     max_depth_grid,
                     class_weight_grid,
                     criterion_grid)

for n_trees, depth, weight, crit in tqdm(list(param_grid), desc="RandomForest grid"):
    model = RandomForestClassifier(
        random_state=21,
        n_estimators=n_trees,
        max_depth=depth,
        class_weight=weight,
        criterion=crit
    )

    cv_scores = cross_val_score(
        estimator=model,
        X=X_train,
        y=y_train,
        cv=5,
        n_jobs=-1
    )

    results.append(
        dict(
            n_estimators=n_trees,
            max_depth=depth,
            class_weight=weight,
            criterion=crit,
            mean_accuracy=cv_scores.mean(),
            std_accuracy=cv_scores.std()
        )
    )

RandomForest grid: 100%|██████████| 784/784 [02:47<00:00,  4.67it/s]

In [13]:
manual_res = pd.DataFrame(results)
manual_res = manual_res.sort_values(by='mean_accuracy', ascending=False)

In [14]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(manual_res)

,n_estimators,max_depth,class_weight,criterion,mean_accuracy,std_accuracy
503,50,28,None,gini,0.904290,0.010961
711,100,31,None,gini,0.903547,0.014380
509,50,30,balanced,gini,0.902817,0.013554
525,50,34,balanced,gini,0.902809,0.013010
743,100,39,None,gini,0.902806,0.010460
751,100,41,None,gini,0.902806,0.010460
731,100,36,None,gini,0.902806,0.010460
735,100,37,None,gini,0.902806,0.010460
759,100,43,None,gini,0.902806,0.010460
775,100,47,None,gini,0.902806,0.010460
739,100,38,None,gini,0.902806,0.010460
747,100,40,None,gini,0.902806,0.010460
767,100,45,None,gini,0.902806,0.010460
783,100,49,None,gini,0.902806,0.010460
779,100,48,None,gini,0.902806,0.010460
507,50,29,None,gini,0.902806,0.011698
771,100,46,None,gini,0.902806,0.010460
763,100,44,None,gini,0.902806,0.010460
755,100,42,None,gini,0.902806,0.010460
517,50,32,balanced,gini,0.902803,0.013267
707,100,30,None,gini,0.902068,0.012843
565,50,44,balanced,gini,0.902065,0.014082
561,50,43,balanced,gini,0.902065,0.014082
557,50,42,balanced,gini,0.902065,0.014082
553,50,41,balanced,gini,0.902065,0.014082
537,50,37,balanced,gini,0.902065,0.014082
541,50,38,balanced,gini,0.902065,0.014082
529,50,35,balanced,gini,0.902065,0.014082
533,50,36,balanced,gini,0.902065,0.014082
569,50,45,balanced,gini,0.902065,0.014082
573,50,46,balanced,gini,0.902065,0.014082
545,50,39,balanced,gini,0.902065,0.014082
549,50,40,balanced,gini,0.902065,0.014082
723,100,34,None,gini,0.902065,0.010759
581,50,48,balanced,gini,0.902065,0.014082
577,50,47,balanced,gini,0.902065,0.014082
585,50,49,balanced,gini,0.902065,0.014082
511,50,30,None,gini,0.902063,0.011989
685,100,25,balanced,gini,0.902063,0.014494
587,50,49,None,gini,0.902063,0.014494
579,50,47,None,gini,0.902063,0.014494
727,100,35,None,gini,0.902063,0.011767
559,50,42,None,gini,0.902063,0.014494
543,50,38,None,gini,0.902063,0.014494
583,50,48,None,gini,0.902063,0.014494
551,50,40,None,gini,0.902063,0.014494
547,50,39,None,gini,0.902063,0.014494
539,50,37,None,gini,0.902063,0.014494
571,50,45,None,gini,0.902063,0.014494
555,50,41,None,gini,0.902063,0.014494
515,50,31,None,gini,0.902063,0.016119
563,50,43,None,gini,0.902063,0.014494
567,50,44,None,gini,0.902063,0.014494
535,50,36,None,gini,0.902063,0.014494
575,50,46,None,gini,0.902063,0.014494
489,50,25,balanced,gini,0.902060,0.016315
697,100,28,balanced,gini,0.902057,0.018234
691,100,26,None,gini,0.901327,0.011225
703,100,29,None,gini,0.901327,0.012834
505,50,29,balanced,gini,0.901325,0.013477
513,50,31,balanced,gini,0.901322,0.015572
715,100,32,None,gini,0.901319,0.013524
701,100,29,balanced,gini,0.901319,0.015782
501,50,28,balanced,gini,0.901319,0.015071
527,50,34,None,gini,0.901316,0.015798
687,100,25,None,gini,0.900587,0.007657
521,50,33,balanced,gini,0.900584,0.013830
689,100,26,balanced,gini,0.900584,0.015513
719,100,33,None,gini,0.900581,0.010974
531,50,35,None,gini,0.900576,0.014859
497,50,27,balanced,gini,0.899851,0.017084
712,100,32,balanced,entropy,0.899846,0.013320
495,50,26,None,gini,0.899843,0.010302
705,100,30,balanced,gini,0.899843,0.016130
666,100,20,None,entropy,0.899843,0.014328
675,100,22,None,gini,0.899843,0.013940
481,50,23,balanced,gini,0.899840,0.012506
656,100,18,balanced,entropy,0.899840,0.012518
713,100,32,balanced,gini,0.899838,0.017495
709,100,31,balanced,gini,0.899838,0.015836
519,50,32,None,gini,0.899835,0.013198
491,50,25,None,gini,0.899835,0.014391
692,100,27,balanced,entropy,0.899105,0.016689
683,100,24,None,gini,0.899102,0.011659
668,100,21,balanced,entropy,0.899100,0.016408
717,100,33,balanced,gini,0.899100,0.013841
699,100,28,None,gini,0.899100,0.013841
680,100,24,balanced,entropy,0.898367,0.015140
778,100,48,None,entropy,0.898362,0.014986
758,100,43,None,entropy,0.898362,0.014986
762,100,44,None,entropy,0.898362,0.014986
754,100,42,None,entropy,0.898362,0.014986
774,100,47,None,entropy,0.898362,0.014986
716,100,33,balanced,entropy,0.898362,0.014813
742,100,39,None,entropy,0.898362,0.014986
730,100,36,None,entropy,0.898362,0.014986
766,100,45,None,entropy,0.898362,0.014986
750,100,41,None,entropy,0.898362,0.014986
726,100,35,None,entropy,0.898362,0.014986
746,100,40,None,entropy,0.898362,0.014986
782,100,49,None,entropy,0.898362,0.014986
770,100,46,None,entropy,0.898362,0.014986
482,50,23,None,entropy,0.898362,0.013028
734,100,37,None,entropy,0.898362,0.014986
738,100,38,None,entropy,0.898362,0.014986
695,100,27,None,gini,0.898359,0.012188
725,100,35,balanced,gini,0.898359,0.013872
718,100,33,None,entropy,0.898359,0.015373
721,100,34,balanced,gini,0.898356,0.016776
664,100,20,balanced,entropy,0.898356,0.020606
698,100,28,None,entropy,0.898356,0.016096
546,50,39,None,entropy,0.898353,0.019381
554,50,41,None,entropy,0.898353,0.019381
566,50,44,None,entropy,0.898353,0.019381
562,50,43,None,entropy,0.898353,0.019381
570,50,45,None,entropy,0.898353,0.019381
550,50,40,None,entropy,0.898353,0.019381
485,50,24,balanced,gini,0.898353,0.017909
526,50,34,None,entropy,0.898353,0.019381
542,50,38,None,entropy,0.898353,0.019381
522,50,33,None,entropy,0.898353,0.019381
534,50,36,None,entropy,0.898353,0.019381
530,50,35,None,entropy,0.898353,0.019381
538,50,37,None,entropy,0.898353,0.019381
558,50,42,None,entropy,0.898353,0.019381
578,50,47,None,entropy,0.898353,0.019381
669,100,21,balanced,gini,0.898353,0.014498
660,100,19,balanced,entropy,0.898353,0.017113
586,50,49,None,entropy,0.898353,0.019381
582,50,48,None,entropy,0.898353,0.019381
574,50,46,None,entropy,0.898353,0.019381
492,50,26,balanced,entropy,0.898351,0.017910
704,100,30,balanced,entropy,0.897621,0.014989
720,100,34,balanced,entropy,0.897621,0.014989
773,100,47,balanced,gini,0.897618,0.014254
769,100,46,balanced,gini,0.897618,0.014254
765,100,45,balanced,gini,0.897618,0.014254
464,50,19,balanced,entropy,0.897618,0.014820
781,100,49,balanced,gini,0.897618,0.014254
757,100,43,balanced,gini,0.897618,0.014254
761,100,44,balanced,gini,0.897618,0.014254
753,100,42,balanced,gini,0.897618,0.014254
777,100,48,balanced,gini,0.897618,0.014254
745,100,40,balanced,gini,0.897618,0.014254
749,100,41,balanced,gini,0.897618,0.014254
741,100,39,balanced,gini,0.897618,0.014254
693,100,27,balanced,gini,0.897618,0.017387
737,100,38,balanced,gini,0.897618,0.014254
514,50,31,None,entropy,0.897615,0.020196
661,100,19,balanced,gini,0.897615,0.013480
733,100,37,balanced,gini,0.897615,0.016426
710,100,31,None,entropy,0.897615,0.016426
518,50,32,None,entropy,0.897613,0.019232
681,100,24,balanced,gini,0.897610,0.019256
478,50,22,None,entropy,0.896886,0.011579
768,100,46,balanced,entropy,0.896880,0.015486
740,100,39,balanced,entropy,0.896880,0.015486
748,100,41,balanced,entropy,0.896880,0.015486
732,100,37,balanced,entropy,0.896880,0.015486
724,100,35,balanced,entropy,0.896880,0.015486
736,100,38,balanced,entropy,0.896880,0.015486
744,100,40,balanced,entropy,0.896880,0.015486
756,100,43,balanced,entropy,0.896880,0.015486
780,100,49,balanced,entropy,0.896880,0.015486
752,100,42,balanced,entropy,0.896880,0.015486
760,100,44,balanced,entropy,0.896880,0.015486
764,100,45,balanced,entropy,0.896880,0.015486
776,100,48,balanced,entropy,0.896880,0.015486
772,100,47,balanced,entropy,0.896880,0.015486
688,100,26,balanced,entropy,0.896880,0.015486
696,100,28,balanced,entropy,0.896880,0.014384
728,100,36,balanced,entropy,0.896880,0.015486
672,100,22,balanced,entropy,0.896877,0.017029
493,50,26,balanced,gini,0.896877,0.016034
468,50,20,balanced,entropy,0.896877,0.017806
499,50,27,None,gini,0.896877,0.013798
702,100,29,None,entropy,0.896877,0.014399
729,100,36,balanced,gini,0.896875,0.015348
684,100,25,balanced,entropy,0.896875,0.017054
714,100,32,None,entropy,0.896875,0.016880
686,100,25,None,entropy,0.896875,0.015348
498,50,27,None,entropy,0.896875,0.018145
676,100,23,balanced,entropy,0.896872,0.018018
523,50,33,None,gini,0.896869,0.015558
674,100,22,None,entropy,0.896142,0.012411
484,50,24,balanced,entropy,0.896139,0.017880
708,100,31,balanced,entropy,0.896137,0.014878
678,100,23,None,entropy,0.896137,0.014878
679,100,23,None,gini,0.896137,0.012248
706,100,30,None,entropy,0.896134,0.016808
722,100,34,None,entropy,0.896131,0.017938
474,50,21,None,entropy,0.896131,0.016350
690,100,26,None,entropy,0.896131,0.016504
667,100,20,None,gini,0.896131,0.014156
670,100,21,None,entropy,0.896128,0.018128
472,50,21,balanced,entropy,0.896123,0.018452
490,50,25,None,entropy,0.895396,0.017189
496,50,27,balanced,entropy,0.895396,0.017649
657,100,18,balanced,gini,0.895393,0.014410
510,50,30,None,entropy,0.895390,0.020444
665,100,20,balanced,gini,0.895390,0.015537
506,50,29,None,entropy,0.895390,0.018444
700,100,29,balanced,entropy,0.894661,0.013576
508,50,30,balanced,entropy,0.894661,0.017484
460,50,18,balanced,entropy,0.894658,0.015310
677,100,23,balanced,gini,0.894652,0.014815
652,100,17,balanced,entropy,0.894650,0.012848
486,50,24,None,entropy,0.894650,0.013875
476,50,22,balanced,entropy,0.894650,0.016588
494,50,26,None,entropy,0.894647,0.017733
483,50,23,None,gini,0.894647,0.011012
473,50,21,balanced,gini,0.894647,0.015236
480,50,23,balanced,entropy,0.894644,0.021529
663,100,19,None,gini,0.894644,0.017276
477,50,22,balanced,gini,0.894641,0.019253
475,50,21,None,gini,0.894641,0.018675
470,50,20,None,entropy,0.894636,0.017954
520,50,33,balanced,entropy,0.893914,0.016027
488,50,25,balanced,entropy,0.893912,0.017690
682,100,24,None,entropy,0.893909,0.015172
671,100,21,None,gini,0.893906,0.013483
694,100,27,None,entropy,0.893906,0.016429
465,50,19,balanced,gini,0.893906,0.013884
673,100,22,balanced,gini,0.893903,0.018058
576,50,47,balanced,entropy,0.893174,0.015985
584,50,49,balanced,entropy,0.893174,0.015985
580,50,48,balanced,entropy,0.893174,0.015985
536,50,37,balanced,entropy,0.893174,0.015985
540,50,38,balanced,entropy,0.893174,0.015985
572,50,46,balanced,entropy,0.893174,0.015985
568,50,45,balanced,entropy,0.893174,0.015985
560,50,43,balanced,entropy,0.893174,0.015985
564,50,44,balanced,entropy,0.893174,0.015985
548,50,40,balanced,entropy,0.893174,0.015985
544,50,39,balanced,entropy,0.893174,0.015985
552,50,41,balanced,entropy,0.893174,0.015985
556,50,42,balanced,entropy,0.893174,0.015985
487,50,24,None,gini,0.893171,0.012746
290,10,24,None,entropy,0.893171,0.014750
479,50,22,None,gini,0.893165,0.015350
512,50,31,balanced,entropy,0.892436,0.017693
524,50,34,balanced,entropy,0.892433,0.016080
528,50,35,balanced,entropy,0.892433,0.016080
516,50,32,balanced,entropy,0.892433,0.015022
649,100,16,balanced,gini,0.892427,0.012004
500,50,28,balanced,entropy,0.892425,0.019678
502,50,28,None,entropy,0.892422,0.019561
640,100,14,balanced,entropy,0.892422,0.014541
469,50,20,balanced,gini,0.892419,0.021213
659,100,18,None,gini,0.892416,0.015501
532,50,36,balanced,entropy,0.891692,0.016310
655,100,17,None,gini,0.891684,0.008987
313,10,30,balanced,gini,0.891684,0.020954
648,100,16,balanced,entropy,0.891678,0.015744
456,50,17,balanced,entropy,0.891678,0.015198
658,100,18,None,entropy,0.891673,0.017597
653,100,17,balanced,gini,0.890938,0.013495
644,100,15,balanced,entropy,0.890938,0.014092
471,50,20,None,gini,0.890938,0.011016
298,10,26,None,entropy,0.890932,0.023139
504,50,29,balanced,entropy,0.890208,0.016685
305,10,28,balanced,gini,0.890202,0.019894
341,10,37,balanced,gini,0.890197,0.023126
329,10,34,balanced,gini,0.890197,0.023126
333,10,35,balanced,gini,0.890197,0.023126
353,10,40,balanced,gini,0.890197,0.023126
381,10,47,balanced,gini,0.890197,0.023126
377,10,46,balanced,gini,0.890197,0.023126
373,10,45,balanced,gini,0.890197,0.023126
369,10,44,balanced,gini,0.890197,0.023126
389,10,49,balanced,gini,0.890197,0.023126
385,10,48,balanced,gini,0.890197,0.023126
357,10,41,balanced,gini,0.890197,0.023126
345,10,38,balanced,gini,0.890197,0.023126
321,10,32,balanced,gini,0.890197,0.023126
325,10,33,balanced,gini,0.890197,0.023126
361,10,42,balanced,gini,0.890197,0.023126
365,10,43,balanced,gini,0.890197,0.023126
337,10,36,balanced,gini,0.890197,0.023126
349,10,39,balanced,gini,0.890197,0.023126
461,50,18,balanced,gini,0.890194,0.016121
277,10,21,balanced,gini,0.889456,0.015893
467,50,19,None,gini,0.889448,0.019361
317,10,31,balanced,gini,0.888718,0.024411
449,50,15,balanced,gini,0.888718,0.016608
462,50,18,None,entropy,0.888710,0.018100
650,100,16,None,entropy,0.888707,0.016706
448,50,15,balanced,entropy,0.888707,0.016217
275,10,20,None,gini,0.887983,0.015258
662,100,19,None,entropy,0.887972,0.019613
459,50,17,None,gini,0.887972,0.012360
445,50,14,balanced,gini,0.887242,0.013764
303,10,27,None,gini,0.887239,0.016517
302,10,27,None,entropy,0.887239,0.021589
306,10,28,None,entropy,0.887237,0.019448
444,50,14,balanced,entropy,0.887231,0.015360
454,50,16,None,entropy,0.887231,0.020049
307,10,28,None,gini,0.887228,0.016442
293,10,25,balanced,gini,0.887226,0.026782
654,100,17,None,entropy,0.887223,0.018386
310,10,29,None,entropy,0.886499,0.017644
452,50,16,balanced,entropy,0.886493,0.014637
318,10,31,None,entropy,0.886488,0.021497
645,100,15,balanced,gini,0.886482,0.015436
309,10,29,balanced,gini,0.885758,0.022426
274,10,20,None,entropy,0.885752,0.007265
334,10,35,None,entropy,0.885752,0.018690
322,10,32,None,entropy,0.885750,0.019712
281,10,22,balanced,gini,0.885744,0.013861
266,10,18,None,entropy,0.885744,0.020288
457,50,17,balanced,gini,0.885741,0.017859
278,10,21,None,entropy,0.885739,0.015784
466,50,19,None,entropy,0.885739,0.023271
326,10,33,None,entropy,0.885012,0.018476
338,10,36,None,entropy,0.885012,0.018476
342,10,37,None,entropy,0.885012,0.018476
651,100,16,None,gini,0.885006,0.013562
289,10,24,balanced,gini,0.885001,0.021450
636,100,13,balanced,entropy,0.884998,0.023545
282,10,22,None,entropy,0.884268,0.013982
117,5,30,balanced,gini,0.884268,0.026363
458,50,17,None,entropy,0.884263,0.016570
297,10,26,balanced,gini,0.884263,0.013852
311,10,29,None,gini,0.884257,0.014101
286,10,23,None,entropy,0.884254,0.024631
646,100,15,None,entropy,0.884254,0.016957
82,5,21,None,entropy,0.884246,0.019299
285,10,23,balanced,gini,0.883538,0.017594
346,10,38,None,entropy,0.883530,0.018403
370,10,44,None,entropy,0.883530,0.018403
374,10,45,None,entropy,0.883530,0.018403
362,10,42,None,entropy,0.883530,0.018403
366,10,43,None,entropy,0.883530,0.018403
382,10,47,None,entropy,0.883530,0.018403
354,10,40,None,entropy,0.883530,0.018403
378,10,46,None,entropy,0.883530,0.018403
350,10,39,None,entropy,0.883530,0.018403
386,10,48,None,entropy,0.883530,0.018403
358,10,41,None,entropy,0.883530,0.018403
390,10,49,None,entropy,0.883530,0.018403
315,10,30,None,gini,0.883525,0.020164
314,10,30,None,entropy,0.883525,0.019880
94,5,24,None,entropy,0.883525,0.016391
323,10,32,None,gini,0.883522,0.018155
138,5,35,None,entropy,0.883522,0.023815
299,10,26,None,gini,0.883519,0.018658
110,5,28,None,entropy,0.883519,0.024293
463,50,18,None,gini,0.883514,0.017771
632,100,12,balanced,entropy,0.883514,0.020100
641,100,14,balanced,gini,0.882792,0.012500
279,10,21,None,gini,0.882787,0.010132
301,10,27,balanced,gini,0.882784,0.021754
330,10,34,None,entropy,0.882784,0.019734
142,5,36,None,entropy,0.882781,0.023810
146,5,37,None,entropy,0.882781,0.023810
453,50,16,balanced,gini,0.882776,0.018486
319,10,31,None,gini,0.882776,0.015772
288,10,24,balanced,entropy,0.882046,0.021408
272,10,20,balanced,entropy,0.882043,0.013194
287,10,23,None,gini,0.882043,0.016002
283,10,22,None,gini,0.882038,0.020707
347,10,38,None,gini,0.882035,0.019749
351,10,39,None,gini,0.882035,0.019749
363,10,42,None,gini,0.882035,0.019749
455,50,16,None,gini,0.882035,0.018919
391,10,49,None,gini,0.882035,0.019749
331,10,34,None,gini,0.882035,0.019749
383,10,47,None,gini,0.882035,0.019749
355,10,40,None,gini,0.882035,0.019749
339,10,36,None,gini,0.882035,0.019749
343,10,37,None,gini,0.882035,0.019749
379,10,46,None,gini,0.882035,0.019749
375,10,45,None,gini,0.882035,0.019749
387,10,48,None,gini,0.882035,0.019749
359,10,41,None,gini,0.882035,0.019749
335,10,35,None,gini,0.882035,0.019749
371,10,44,None,gini,0.882035,0.019749
367,10,43,None,gini,0.882035,0.019749
450,50,15,None,entropy,0.882032,0.017878
284,10,23,balanced,entropy,0.881311,0.020815
109,5,28,balanced,gini,0.881305,0.020431
130,5,33,None,entropy,0.881300,0.024073
327,10,33,None,gini,0.881294,0.017775
436,50,12,balanced,entropy,0.881286,0.022970
113,5,29,balanced,gini,0.880567,0.027843
182,5,46,None,entropy,0.880559,0.024340
158,5,40,None,entropy,0.880559,0.024340
150,5,38,None,entropy,0.880559,0.024340
154,5,39,None,entropy,0.880559,0.024340
178,5,45,None,entropy,0.880559,0.024340
186,5,47,None,entropy,0.880559,0.024340
194,5,49,None,entropy,0.880559,0.024340
174,5,44,None,entropy,0.880559,0.024340
190,5,48,None,entropy,0.880559,0.024340
114,5,29,None,entropy,0.880559,0.021970
166,5,42,None,entropy,0.880559,0.024340
162,5,41,None,entropy,0.880559,0.024340
170,5,43,None,entropy,0.880559,0.024340
296,10,26,balanced,entropy,0.880556,0.024122
647,100,15,None,gini,0.880556,0.019180
292,10,25,balanced,entropy,0.880548,0.025714
280,10,22,balanced,entropy,0.880548,0.014466
642,100,14,None,entropy,0.880542,0.021665
121,5,31,balanced,gini,0.879821,0.021305
122,5,31,None,entropy,0.879813,0.026031
258,10,16,None,entropy,0.879813,0.021001
637,100,13,balanced,gini,0.879810,0.017084
270,10,19,None,entropy,0.879807,0.026192
126,5,32,None,entropy,0.879807,0.028098
294,10,25,None,entropy,0.879086,0.018394
165,5,42,balanced,gini,0.879078,0.021827
173,5,44,balanced,gini,0.879078,0.021827
181,5,46,balanced,gini,0.879078,0.021827
125,5,32,balanced,gini,0.879078,0.021827
161,5,41,balanced,gini,0.879078,0.021827
185,5,47,balanced,gini,0.879078,0.021827
189,5,48,balanced,gini,0.879078,0.021827
157,5,40,balanced,gini,0.879078,0.021827
193,5,49,balanced,gini,0.879078,0.021827
141,5,36,balanced,gini,0.879078,0.021827
137,5,35,balanced,gini,0.879078,0.021827
153,5,39,balanced,gini,0.879078,0.021827
145,5,37,balanced,gini,0.879078,0.021827
149,5,38,balanced,gini,0.879078,0.021827
169,5,43,balanced,gini,0.879078,0.021827
133,5,34,balanced,gini,0.879078,0.021827
129,5,33,balanced,gini,0.879078,0.021827
177,5,45,balanced,gini,0.879078,0.021827
118,5,30,None,entropy,0.879078,0.022354
264,10,18,balanced,entropy,0.879061,0.024002
440,50,13,balanced,entropy,0.878337,0.019956
134,5,34,None,entropy,0.878334,0.025979
295,10,25,None,gini,0.878329,0.020564
102,5,26,None,entropy,0.878320,0.017107
451,50,15,None,gini,0.878320,0.019371
262,10,17,None,entropy,0.878315,0.021683
90,5,23,None,entropy,0.876853,0.016515
291,10,24,None,gini,0.876847,0.022341
441,50,13,balanced,gini,0.876839,0.020061
261,10,17,balanced,gini,0.876828,0.026308
98,5,25,None,entropy,0.876106,0.017060
70,5,18,None,entropy,0.876106,0.011219
268,10,19,balanced,entropy,0.876106,0.020314
254,10,15,None,entropy,0.875366,0.018615
442,50,13,None,entropy,0.875360,0.020876
260,10,17,balanced,entropy,0.875355,0.025003
271,10,19,None,gini,0.875349,0.024118
380,10,47,balanced,entropy,0.874628,0.024854
372,10,45,balanced,entropy,0.874628,0.024854
356,10,41,balanced,entropy,0.874628,0.024854
352,10,40,balanced,entropy,0.874628,0.024854
332,10,35,balanced,entropy,0.874628,0.024854
360,10,42,balanced,entropy,0.874628,0.024854
344,10,38,balanced,entropy,0.874628,0.024854
340,10,37,balanced,entropy,0.874628,0.024854
384,10,48,balanced,entropy,0.874628,0.024854
388,10,49,balanced,entropy,0.874628,0.024854
324,10,33,balanced,entropy,0.874628,0.024854
364,10,43,balanced,entropy,0.874628,0.024854
348,10,39,balanced,entropy,0.874628,0.024854
320,10,32,balanced,entropy,0.874628,0.024854
336,10,36,balanced,entropy,0.874628,0.024854
376,10,46,balanced,entropy,0.874628,0.024854
368,10,44,balanced,entropy,0.874628,0.024854
300,10,27,balanced,entropy,0.874625,0.025317
107,5,27,None,gini,0.874619,0.011933
111,5,28,None,gini,0.874619,0.017852
106,5,27,None,entropy,0.873879,0.024881
265,10,18,balanced,gini,0.873879,0.017460
83,5,21,None,gini,0.873876,0.019684
638,100,13,None,entropy,0.873870,0.019752
78,5,20,None,entropy,0.873152,0.014700
312,10,30,balanced,entropy,0.873146,0.025497
316,10,31,balanced,entropy,0.873146,0.023713
304,10,28,balanced,entropy,0.873143,0.021165
308,10,29,balanced,entropy,0.873143,0.024971
119,5,30,None,gini,0.873135,0.017239
276,10,21,balanced,entropy,0.873135,0.021103

## 6. Predictions

1. Choose the best model and use it to make predictions for the test dataset.
2. Calculate the final accuracy.

In [15]:
best_forest = RandomForestClassifier(random_state=21,
                            n_estimators=100,
                            max_depth=33, 
                            class_weight=None,
                            criterion='gini')
best_forest.fit(X_train, y_train)
best_prediction = best_forest.predict(X_test)

accuracy_score(y_test, best_prediction)

0.9349112426035503